services:
  application: 
    build: .
    container_name: development
    env_file: 
      - ./.env
    volumes: 
      - ../:/workspaces/
    networks: 
      - trans_net
    expose:
      - 8000
    labels:
      - 'devcontainer.local_folder=/home/fheid/transcendence'
      - 'devcontainer.config_file=/home/fheid/transcendence/.devcontainer/devcontainer.json'
  database:
    container_name: django_db
    image: postgres:latest
    env_file:
      - .env
    networks:
      - trans_net
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - ./../src:/var/www/html/frontend/
    networks:
      - trans_net
    expose:
      - 8090
    ports:
      - "8090:8090"
  adminer: 
    container_name: adminer
    image: adminer
    networks: 
      - trans_net
    ports: 
      - "8080:8080"
  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - redis_data:/data
    expose:
      - 6379
    networks:
     - trans_net
  blockchain:
    build: ./requirements/blockchain
    container_name: blockchain
    networks:
      - trans_net
    ports:
      - "5000:5000"

networks: 
  trans_net: 
    driver: bridge
volumes:
  postgres_data:
  redis_data:
