services:
  application: 
    build: .
    container_name: development
    env_file: 
      - ./.env
    volumes: 
      - ../:/workspaces/
    networks: 
      - trans_net
    expose:
      - 8000
      - 8001
    labels:
      - 'devcontainer.local_folder=/home/fwechsle/ft_trans'
      - 'devcontainer.config_file=/home/fwechsle/ft_trans/.devcontainer/devcontainer.json'
  database:
    container_name: django_db
    image: postgres:latest
    env_file:
      - .env
    networks:
      - trans_net
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - ./../src:/var/www/html/frontend/
    networks:
      - trans_net
    expose:
      - 8090
    ports:
      - "8090:8090"
  adminer: 
    container_name: adminer
    image: adminer
    networks: 
      - trans_net
    ports: 
      - "8080:8080"
networks: 
  trans_net: 
    driver: bridge
volumes:
  postgres_data:
