services:
  application: 
    build: .
    container_name: development
    env_file: 
      - ./.env
    volumes: 
      - ../:/workspaces/
    networks: 
      - trans_net
    expose:
      - 8000
    labels:
      - 'devcontainer.local_folder=/home/felix/Dokumente/ft_transendence'
      - 'devcontainer.config_file=/home/felix/Dokumente/ft_transendence/.devcontainer/devcontainer.json'
  database:
    container_name: django_db
    image: postgres:latest
    env_file:
      - .env
    networks:
      - trans_net
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
    networks:
      - trans_net
    expose:
      - 8090
    ports:
      - "8090:8090"
networks: 
  trans_net: 
    driver: bridge
volumes:
  postgres_data:
