services:
  application: 
    build: .
    container_name: development
    env_file: 
      - ./.env
    ports: 
      - "8090:8090"
      - "443:443"
    volumes: 
      - ../:/workspaces/
    networks: 
      - trans_net

networks: 
  trans_net: 
    driver: bridge
